name: Lint
on:
  push:
    branches:
      - main

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.4'
          cache: false

      - name: Check out code
        uses: actions/checkout@v3

      - name: Clear Go cache
        run: go clean -cache

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.45.0
          args: --fix